### ISSUE TITLE
KeyError in contract_leaves_until_balanced_or_none

### ISSUE THREAD

**Issue by lieuzhenghong** [lieuzhenghong/human-compactness#3]
@drdeford, I ran into this issue while trying to generate ensembles for the state of Georgia:

```
False
[1615, 3]
Traceback (most recent call last):
  File "Generate_Ensembles.py", line 66, in <module>
    totpop / num_districts, "FL5001", .02, 1)
  File "/home/lieu/anaconda3/envs/human-compactness/lib/python3.7/site-packages/gerrychain/tree.py", line 222, in recursive_tree_part
    node_repeats=node_repeats,
  File "/home/lieu/anaconda3/envs/human-compactness/lib/python3.7/site-packages/gerrychain/tree.py", line 132, in bipartition_tree
    balanced_subtree = contract_leaves_until_balanced_or_none(h, choice=choice)
  File "/home/lieu/anaconda3/envs/human-compactness/lib/python3.7/site-packages/gerrychain/tree.py", line 60, in contract_leaves_until_balanced_or_none
    parent = pred[leaf]
KeyError: 40790
```

I must have done something wrong somehow --- could you take a look at the file?

**Comment by drdeford** [comment]
The problem there is that the dual graph is disconnected because there are some islands (the two lines that printed initially are telling you that the graph is not connected and that the sizes of the two components are 1615 nodes and 3 nodes. Some approaches for dealing with this problem in general are described here: https://gerrychain.readthedocs.io/en/latest/user/islands.html

When I ran it, I just deleted the three node island from the graph (lines 56-57 in Generate_Ensembles) but you could also look at the shapefile to decide where to connect those tracts.
